# Generated by Django 4.2.7 on 2023-11-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_review_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(null=True, verbose_name='Rating (1 - 5)'),
        ),
    ]
