# Generated by Django 4.2.7 on 2023-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
