# Generated by Django 4.2.7 on 2023-11-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
